FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
COPY ./app /app

RUN apt-get update -y && \
    apt-get install -y curl

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
