### Get Drivers
GET http://localhost:8000/drivers/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjMsInVzZXJuYW1lIjoiam9hby5zaWx2YSIsImV4cCI6MTczMTkyNzI5Mn0.brYjX65tdEHZku0A0wY_bLxuZ1N-hfmIgQP2HG4Rhbw
ontent-Type: application/json

### Get Locations
GET http://localhost:8000/locations HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjMsInVzZXJuYW1lIjoiam9hby5zaWx2YSIsImV4cCI6MTczMTg3NTA4NH0.WNFYoPEtronvE_r8DDuGJdCBqK-L_DewX14372omnVI
ontent-Type: application/json

### Get Pricings
GET http://localhost:8000/pricings HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjMsInVzZXJuYW1lIjoiam9hby5zaWx2YSIsImV4cCI6MTczMTg3NTA4NH0.WNFYoPEtronvE_r8DDuGJdCBqK-L_DewX14372omnVI
ontent-Type: application/json

### Get Rides
GET http://localhost:8000/rides HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjMsInVzZXJuYW1lIjoiam9hby5zaWx2YSIsImV4cCI6MTczMTg3NTA4NH0.WNFYoPEtronvE_r8DDuGJdCBqK-L_DewX14372omnVI
ontent-Type: application/json
